server:
    port: 80

spring:
    datasource:
        url: jdbc:mysql://agent-db.c7kya4auwp7k.ap-northeast-2.rds.amazonaws.com:3306/agent
        username: admin
        password: dlalsdud1!
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
